version: '2'
services:
  wordpress:
    build: ./wordpress
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=wordpressuser
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress-data:/var/www/html
    ports:
      - 80:80
    networks:
      - back-end
    links:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpressuser
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - back-end
volumes:
  wordpress-data:
    driver: local
  mysql-data:
    driver: local
networks:
  back-end:
    driver: bridge
